# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  effect = {
    pname = "effect";
    version = "813eb2fff9c4efa79bd8b1651a78fb8fd7bc25a4";
    src = fetchFromGitHub {
      owner = "ethanthoma";
      repo = "effect";
      rev = "813eb2fff9c4efa79bd8b1651a78fb8fd7bc25a4";
      fetchSubmodules = false;
      sha256 = "sha256-ZssdoDjuiLXvlNfZLpPMZDFyjvMGqYue7nYm3XjwK2Y=";
    };
    date = "2025-02-02";
  };
  gleam-stdlib = {
    pname = "gleam-stdlib";
    version = "9548d28cc2cf6991bdc6b91aeb27d2d7adde040b";
    src = fetchFromGitHub {
      owner = "gleam-lang";
      repo = "stdlib";
      rev = "9548d28cc2cf6991bdc6b91aeb27d2d7adde040b";
      fetchSubmodules = false;
      sha256 = "sha256-FkOh28tsEwutdt83eBGNieDO8BZBp8skaYy5mEO7638=";
    };
    date = "2025-02-04";
  };
}
